on:
  pull_request:
    types: [opened, synchronize]

jobs:
  evaluator_job:
    runs-on: ubuntu-18.04
    name: Evaluator job
    steps:
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'
      - name: Static code analysis step
        uses: betrybe/stylelint-linter-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Static code analysis step
        uses: betrybe/eslint-linter-action@v2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        if: steps.wait-for-build.outputs.conclusion == 'success'
      - name: React Scripts evaluator step
        id: react-scripts
        uses: betrybe/react-scripts-evaluator-action@v1
        if: steps.wait-for-build.outputs.conclusion == 'success'
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v1
        if: steps.wait-for-build.outputs.conclusion == 'success'
        with:
          evaluation-data: ${{ steps.react-scripts.outputs.result }}
          environment: staging
          pr-number: ${{ steps.react-scripts.outputs.pr-number }}
